[package]
name = "luki_os"
version = "0.1.0"
edition = "2021"

[dependencies]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[[bin]]
name = "luki_os"
test = false
bench = false

[dependencies.bootloader]
version = "0.9"
features = ["map_physical_memory"]


